// This file is autogenerated, DO NOT EDIT
// connector/apis/update-connector-error-api.asciidoc:81

[source, python]
----
resp = client.connector.update_error(
    connector_id="my-connector",
    error="Houston, we have a problem!",
)
print(resp)
----
